name: Linter

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.sh'
      - '.github/workflows/linter.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.sh'
      - '.github/workflows/linter.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install linter
        run: sudo apt install shellcheck

      # - name: Run linter
      #   run: |
      #     shellcheck ignfr2map.sh
      #     shellcheck scripts/*.sh
