name: Linter

on:
  push:
    branches: [ master ]
    paths:
      - '**.sh'
      - '.github/workflows/linter.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**.sh'
      - '.github/workflows/linter.yml'

jobs:
  shell-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install linter
        run: sudo apt install shellcheck

      - name: Run linter
        run: |
          shellcheck ignfr2map.sh
          shellcheck scripts/*.sh
