name: Run and publish

on:
  schedule:
    - cron: "0 0 1 * *"  # monthly
  workflow_dispatch:     # to trigger manually
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/run_n_publish.yml'

jobs:
  run:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Rename env file
        run: mv example.env .env

      - name: Run it
        run: bash ./ignfr2map.sh

      - name: List temp
        run: ls -R _temp/

      - name: List final output
        run: ls -R final/

      - name: Deploy to GitHub Pages
        run: ghp-import --force --no-jekyll --push final
